"""added thumbnail url

Revision ID: 43c92d0d7345
Revises: 7c10c74cb0ca
Create Date: 2024-05-15 14:15:33.632884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c92d0d7345'
down_revision: Union[str, None] = '7c10c74cb0ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('thumbnail_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'thumbnail_url')
    # ### end Alembic commands ###
