"""changed movie table

Revision ID: a47d486078f8
Revises: 536c2126e2fb
Create Date: 2024-05-03 14:56:02.215432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47d486078f8'
down_revision: Union[str, None] = '536c2126e2fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_date',
               existing_type=sa.DATE(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_date',
               existing_type=sa.Text(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
