"""video urls added

Revision ID: e97fbb614928
Revises: 7c28dd2578a5
Create Date: 2024-05-15 15:53:51.814183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97fbb614928'
down_revision: Union[str, None] = '7c28dd2578a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('video_url', sa.String(length=255), nullable=True))
    op.add_column('series', sa.Column('video_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'video_url')
    op.drop_column('movies', 'video_url')
    # ### end Alembic commands ###
